```{r outtabsubfuncaf, cache=cacheon}
survmysub <- function(time, event, xvar, xvarname, matchdata) {
  levs <- levels(pdata %>% pull(!!sym(xvar)))

  out <- data.frame(matrix(NA, ncol = 6, nrow = length(levs) + 1))
  colnames(out) <- c("Subgroup", "HR (95% CI)", "p", "coef", "lci", "uci")

  out[1, 1] <- xvarname

  for (i in seq_along(levs)) {
    out[1 + i, 1] <- paste0("  ", levs[i])

    mod <- coxme(formula(paste0(
      "Surv(", time, ",",
      event, "=='Yes') ~ ddr_digoxin * relevel(", xvar, ", ref = '", levs[i], "') + (1 | par)"
    )),
    data = matchdata
    )

    se <- sqrt(vcov(mod)[1])

    out[1 + i, 2] <- paste0(
      dF(exp(mod$coefficients[1]), dig = 2),
      " (", dF(exp(mod$coefficients[1] - global_z05 * se), dig = 2),
      "-", dF(exp(mod$coefficients[1] + global_z05 * se), dig = 2), ")"
    )

    out[1 + i, 4] <- mod$coefficients[1]
    out[1 + i, 5] <- mod$coefficients[1] - global_z05 * se
    out[1 + i, 6] <- mod$coefficients[1] + global_z05 * se

    if (i == 1) {
      pint <- car::Anova(mod, type = "III", test.statistic = "Wald")

      out[1, 3] <- dF(pint[3, 3], dig = 3, p = TRUE)
    }
  }
  return(out)
}

survmysub2 <- function(time2, event2, matchdata2) {
  forestdata <- survmysub(
    time = time2,
    event = event2,
    xvar = "shf_sex",
    xvarname = "Gender",
    matchdata = matchdata2
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_age_cat",
      xvarname = "Age (years)",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_location",
      xvarname = "Location",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_durationhf",
      xvarname = "Duration of HF (mo)",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_nyha_cat",
      xvarname = "NYHA class",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_ef",
      xvarname = "EF (%)",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_heartrate_cat",
      xvarname = "Heart rate (beats/min)",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_ckd",
      xvarname = "CKD",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_bmi_cat",
      xvarname = "BMI (kg/m2)",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_sos_com_ihd",
      xvarname = "IHD",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_rasarni",
      xvarname = "RASi/ARNi",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_bbl",
      xvarname = "Beta-blocker",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_mra",
      xvarname = "MRA",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_device_cat",
      xvarname = "Device therapy",
      matchdata = matchdata2
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_map_cat",
      xvarname = "MAP",
      matchdata = matchdata2
    )
  )
}
```

```{r outtabsubfuncafplot, cache=cacheon, dependson="outtabsubfuncaf"}
plotforest <- function(forestdata, xlabadj = 0.07) {
  cextext <- 0.9

  minmy <- round(exp(min(forestdata$lci, na.rm = T)), 1)
  maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

  # c(bottom, left, top, right)
  par(mar = c(5, 17, 1, 2) + 0.2)


  plot(rev(forestdata$coef), 1:nrow(forestdata),
    cex = 1.2,
    xlim = c(
      log(minmy),
      log(maxmy)
    ),
    xlab = NA,
    ylim = c(1, nrow(forestdata) + .4),
    axes = FALSE,
    ylab = NA,
    main = NA,
    type = "p",
    pch = 22,
    bg = global_kicols[1],
    col = global_kicols[1]
  )

  for (i in 1:nrow(forestdata)) {
    if (!is.na(rev(forestdata$lci)[i])) {
      matplot(c(rev(forestdata$lci)[i], rev(forestdata$uci)[i]), c(i, i),
        type = "l", add = TRUE, col = global_kicols[1], cex = 2
      )
    }
  }

  matplot(c(log(1), log(1)), c(-1, nrow(forestdata) + 1), type = "l", lwd = 1, lty = 1, add = TRUE, col = 1)

  axismy <- seq(minmy, maxmy, 0.1)
  axismy2 <- axismy
  axismy2[!axismy %in% c(minmy, maxmy)] <- NA

  axis(1,
    cex.axis = cextext, at = log(axismy),
    labels = axismy2
  )
  axis(1,
    cex.axis = cextext, at = log(1),
    labels = 1
  )

  axis(2,
    at = c(1:nrow(forestdata), nrow(forestdata) + 1),
    labels = c(rev(forestdata$Subgroup), "Subgroup"),
    cex.axis = cextext, tick = FALSE, las = 2, line = 16, hadj = 0
  )

  axis(2,
    at = c(1:nrow(forestdata), nrow(forestdata) + 1),
    labels = c(rev(forestdata$`HR (95% CI)`), "Hazard Ratio (95% CI)"),
    cex.axis = cextext, tick = FALSE, las = 2, line = 6, hadj = 0.5
  )

  axis(2,
    at = c(1:nrow(forestdata), nrow(forestdata) + 1),
    labels = c(rev(forestdata$p), "P-value"),
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5
  )

  axis(1,
    at = xlabadj, cex.axis = cextext,
    labels = "Digoxin  No Digoxin", line = 1, tick = FALSE
  )
  axis(1,
    at = 0, cex.axis = cextext,
    labels = "better", line = 2, tick = FALSE
  )
}
```

```{r outtabsubdeathhfhospaf, cache=cacheon, dependson="outtabsubfuncaf"}
hfhospdeathforest <- survmysub2(
  time2 = "sos_outtime_hosphf",
  event2 = "sos_out_deathhosphf",
  matchdata = matchp_af
)
```

```{r forestdeathhfhospaf, cache=cacheon, dependson="outtabsubfuncafplot", fig.cap="Subgroups First HF hospitalization/death - Patients with AF", fig.width=5, fig.height=10}
plotforest(hfhospdeathforest)
```

```{r outtabsubdeathaf, cache=cacheon, dependson="outtabsubfuncaf"}
deathforest <- survmysub2(
  time2 = "sos_outtime_death",
  event2 = "sos_out_death",
  matchdata = matchp_af
)
```

```{r forestdeathaf, cache=cacheon, dependson="outtabsubfuncafplot", fig.cap="Subgroups Death - Patients with AF", fig.width=5, fig.height=10}
plotforest(deathforest, xlabadj = 0.1)
```

```{r outtabsubhfhospaf, cache=cacheon, dependson="outtabsubfuncaf"}
hfhospforest <- survmysub2(
  time2 = "sos_outtime_hosphf",
  event2 = "sos_out_hosphf",
  matchdata = matchp_af
)
```

```{r foresthfhospaf, cache=cacheon, dependson="outtabsubfuncafplot", fig.cap="Subgroups First HF hospitalization - Patients with AF", fig.width=5, fig.height=10}
plotforest(hfhospforest, xlabadj = 0.1)
```

```{r outtabsubdeathhfhospnoaf, cache=cacheon, dependson="outtabsubfuncaf"}
hfhospdeathforest <- survmysub2(
  time2 = "sos_outtime_hosphf",
  event2 = "sos_out_deathhosphf",
  matchdata = matchp_noaf
)
```

```{r forestdeathhfhospnoaf, cache=cacheon, dependson="outtabsubfuncafplot", fig.cap="Subgroups First HF hospitalization/death - Patients without AF", fig.width=5, fig.height=10}
plotforest(hfhospdeathforest, xlabadj = 0.19)
```

```{r outtabsubdeathnoaf, cache=cacheon, dependson="outtabsubfuncaf"}
deathforest <- survmysub2(
  time2 = "sos_outtime_death",
  event2 = "sos_out_death",
  matchdata = matchp_noaf
)
```

```{r forestdeathnoaf, cache=cacheon, dependson="outtabsubfuncafplot", fig.cap="Subgroups Death - Patients without AF", fig.width=5, fig.height=10}
plotforest(deathforest, xlabadj = 0.18)
```

```{r outtabsubhfhospnoaf, cache=cacheon, dependson="outtabsubfuncaf"}
hfhospforest <- survmysub2(
  time2 = "sos_outtime_hosphf",
  event2 = "sos_out_hosphf",
  matchdata = matchp_noaf
)
```

```{r foresthfhospnoaf, cache=cacheon, dependson="outtabsubfuncafplot", fig.cap="Subgroups First HF hospitalization - Patients without AF", fig.width=5, fig.height=10}
plotforest(hfhospforest, xlabadj = 0.25)
```

